### ISSUE TITLE
[Errata]: Weirdness during experimenting

### ISSUE THREAD

**Issue by Rueful-Pi** [raspberrypipress/official-raspberry-pi-beginners-guide-5e#5]
### What format of the book has this error? You may select more than one option.

Print

### What language of the book has this error?

English (EN)

### Page Number or Section

pg 171 Physical computing with the Sense HAT

### Detailed description

Not sure if this belongs in "Issues" but, I didn't see a general discussions tab.

During experimenting as suggested on page 171, I found that the LEDs turned off with any RGB value of 47 and below. So, "sense.clear(47, 47, 47)" would turn the panel off, while (48, 48, 48) would show a much dimmed white. Is this an error or just voltage too low for LEDs to operate?  Curious, indeed.

**Comment by bjepson** [comment]
Thanks, @Rueful-Pi. There is an Astro Pi forum that is used for discussions of the Sense HAT itself, and someone on that forum may have some insights: https://forums.raspberrypi.com/viewforum.php?f=104

There is also a GitHub repository just for the Python API, in case this is an issue with the Python API and not with the hardware. There is a closed discussion about the _pack_bin method that handles the RGB colour values, and this may illuminate (pardon the pun) things: https://github.com/astro-pi/python-sense-hat/issues/31

Best,

Brian

**Comment by Rueful-Pi** [comment]
Thanks @bjepson for the info and links will definitely check all that out.
